"""طبقة التفاعل مع GitHub: فحص المستودعات واكتشاف النواقص وفتح Pull Requests.

GitHub API layer for Celia Repo Agent.

Responsibilities:
  * List the repositories owned by the authenticated user.
  * Audit each repository for common gaps (missing README / .gitignore /
    CI workflow, open issues).
  * Create fix branches, commit files and open pull requests.
  * Post AI-suggested solutions as comments on open issues.
"""

import datetime as _dt
import logging
from typing import Any, Dict, List, Optional

from github import Auth, Github, GithubException

from config import Config

logger = logging.getLogger(__name__)


class JobLogDownloadError(RuntimeError):
    """فشل تنزيل سجل وظيفة (job log) من GitHub Actions."""

# Marker label used on PRs/comments created by the agent, so repeated runs
# can detect work that was already submitted instead of duplicating it.
AGENT_BOT_SIGNATURE = "🤖 **Auto-Fix generated by Celia Repo Agent**"


class GitHubService:
    """Thin wrapper around PyGithub with the audit/fix operations we need."""

    def __init__(self) -> None:
        auth = Auth.Token(Config.GITHUB_TOKEN)
        # `per_page=100` reduces the number of paginated requests.
        self.client = Github(auth=auth, per_page=100)
        self.user = self.client.get_user()
        logger.info("تم تسجيل الدخول إلى GitHub باسم: %s", self.user.login)

    # ------------------------------------------------------------------ #
    # Repository discovery
    # ------------------------------------------------------------------ #
    def get_all_repositories(self) -> List[Any]:
        """استرجاع جميع المستودعات التي يملكها المستخدم (بدون المستودعات المنسَّقة)."""
        owned: List[Any] = []
        for repo in self.user.get_repos(affiliation="owner"):
            try:
                if repo.owner.login == self.user.login and not repo.archived:
                    owned.append(repo)
            except GithubException as exc:  # pragma: no cover - defensive
                logger.warning("تعذّرت قراءة مستودع: %s", exc)
        return owned

    def get_repository(self, identifier: str) -> Optional[Any]:
        """استرجاع مستودع واحد محدد للفحص المستهدف.

        يقبل ``OWNER/NAME`` (استعلام مباشر عبر الـ API) أو اسم المستودع فقط
        (بحث بين المستودعات المملوكة، بنفس فلاتر :meth:`get_all_repositories`).

        Returns:
            المستودع المطلوب أو ``None`` إن لم يوجد / لم يكن متاحاً للتوكن.
        """
        identifier = (identifier or "").strip()
        if not identifier:
            return None

        if "/" in identifier:
            try:
                return self.client.get_repo(identifier)
            except GithubException as exc:
                logger.warning("تعذّر جلب المستودع %s: %s", identifier, exc)
                return None

        # اسم فقط: ابحث بين المستودعات المملوكة (مطابقة غير حساسة للحالة).
        wanted = identifier.lower()
        for repo in self.get_all_repositories():
            try:
                if repo.name.lower() == wanted or repo.full_name.lower() == wanted:
                    return repo
            except GithubException as exc:  # pragma: no cover - defensive
                logger.warning("تعذّرت قراءة مستودع: %s", exc)
        logger.warning("لم يُعثر على مستودع مملوك باسم: %s", identifier)
        return None

    # ------------------------------------------------------------------ #
    # Auditing
    # ------------------------------------------------------------------ #
    def audit_repository(self, repo: Any) -> Dict[str, Any]:
        """فحص المستودع لاكتشاف النواقص والمشاكل.

        Returns:
            Dict containing repo metadata and a list of detected issues.
        """
        issues: List[Dict[str, Any]] = []

        # 1) README (any common variant counts as present)
        if not self._has_any_file(repo, ["README.md", "README.rst", "README.txt", "README"]):
            issues.append({"type": "missing_file", "target": "README.md"})

        # 2) .gitignore
        if not self._has_any_file(repo, [".gitignore"]):
            issues.append({"type": "missing_file", "target": ".gitignore"})

        # 3) CI/CD (GitHub Actions workflows)
        try:
            workflows = repo.get_workflows()
            if workflows.totalCount == 0:
                issues.append(
                    {"type": "missing_workflow", "target": ".github/workflows/ci.yml"}
                )
        except GithubException:
            # Repos without the Actions feature enabled, etc.
            pass

        # 4) Open issues (excluding pull requests)
        try:
            open_issues = repo.get_issues(state="open")
            for issue in open_issues:
                if not issue.pull_request:
                    issues.append(
                        {
                            "type": "open_issue",
                            "id": issue.number,
                            "title": issue.title,
                            "body": issue.body or "",
                        }
                    )
        except GithubException:
            pass

        return {
            "repo_name": repo.name,
            "full_name": repo.full_name,
            "default_branch": repo.default_branch,
            "issues": issues,
        }

    @staticmethod
    def _has_any_file(repo: Any, paths: List[str]) -> bool:
        """هل يوجد أي من المسارات المحددة في المستودع (على الفرع الافتراضي)؟"""
        for path in paths:
            try:
                repo.get_contents(path)
                return True
            except GithubException:
                continue
        return False

    # ------------------------------------------------------------------ #
    # Dependabot security alerts
    # ------------------------------------------------------------------ #
    def get_dependabot_alerts(
        self, repo: Any, ecosystem: str = "pip"
    ) -> List[Dict[str, Any]]:
        """جلب تنبيهات Dependabot المفتوحة الخاصة بمنظومة حزم واحدة.

        يتطلب ذلك صلاحية ``security_events`` على الـ Personal Access Token
        (أو ``security-events: read`` في GitHub Actions).

        Args:
            repo: كائن المستودع (PyGithub).
            ecosystem: اسم المنظومة مثل ``pip`` أو ``npm``.

        Returns:
            قائمة بقواميس تصف الثغرات: رقم التنبيه، اسم الحزمة، الخطورة،
            النطاق المُصاب، النسخة المُصلِحة، ملخص الثغرة، معرّف GHSA،
            ومسار ملف الاعتماديات (manifest).
        """
        alerts: List[Dict[str, Any]] = []
        try:
            dependabot_alerts = repo.get_dependabot_alerts(state="open")
            for alert in dependabot_alerts:
                try:
                    vuln = alert.security_vulnerability
                    package = vuln.package
                    # تصفية ثغرات المنظومة المطلوبة فقط (pip/npm...).
                    if (package.ecosystem or "").lower() != ecosystem.lower():
                        continue

                    # ملاحظة: في PyGithub تكون first_patched_version قاموساً
                    # مثل {"identifier": "2.3.4"} وليست كائناً.
                    patched_info = vuln.first_patched_version or {}
                    patched_ver = (
                        patched_info.get("identifier")
                        if isinstance(patched_info, dict)
                        else getattr(patched_info, "identifier", None)
                    )

                    manifest = "package.json" if ecosystem.lower() == "npm" else "requirements.txt"
                    try:
                        manifest = alert.dependency.manifest_path or manifest
                    except GithubException:
                        pass

                    alerts.append(
                        {
                            "number": alert.number,
                            "package_name": package.name,
                            "severity": vuln.severity,
                            "vulnerable_range": vuln.vulnerable_version_range,
                            "patched_version": patched_ver,
                            "summary": alert.security_advisory.summary,
                            "ghsa_id": alert.security_advisory.ghsa_id,
                            "manifest": manifest,
                        }
                    )
                except GithubException:
                    # تنبيه واحد غير قابل للقراءة يجب ألا يُسقط البقية.
                    continue
        except GithubException as exc:
            # 403/404: التوكن يفتقد صلاحية security_events أو Dependabot
            # غير مفعّل على المستودع — يتم التخطّي بهدوء.
            logger.info(
                "تعذّر جلب تنبيهات Dependabot لـ %s (قد يلزم تفعيل "
                "Dependabot أو منح صلاحية security_events): %s",
                repo.full_name,
                exc.status if hasattr(exc, "status") else exc,
            )
        return alerts

    # ------------------------------------------------------------------ #
    # GitHub Actions runs / jobs / logs (used by the CI healer)
    # ------------------------------------------------------------------ #
    def get_recent_failed_runs(
        self, repo: Any, lookback_days: int = 14, max_runs: int = 5
    ) -> List[Any]:
        """استرجاع أحدث تشغيلات GitHub Actions الفاشلة على الفرع الافتراضي.

        يتم استبعاد التشغيلات الداخلية لـ Dependabot (مسارات تبدأ بـ
        ``dynamic/``) لأنها ليست workflows يملكها المستخدم.

        Args:
            repo: كائن المستودع.
            lookback_days: عدد الأيام الماضية للبحث (افتراضي 14).
            max_runs: الحد الأقصى لعدد التشغيلات الفاشلة المُرجعة.

        Returns:
            قائمة بكائنات PyGithub ``WorkflowRun`` الفاشلة (الأحدث أولاً).
        """
        since = _dt.datetime.now(_dt.timezone.utc) - _dt.timedelta(days=lookback_days)
        failed: List[Any] = []
        try:
            runs = repo.get_workflow_runs(branch=repo.default_branch, status="completed")
            for run in runs:
                created = getattr(run, "created_at", None)
                if created and created < since:
                    break  # القائمة مرتبة تنازلياً (الأحدث أولاً).
                path = (getattr(run, "path", "") or "")
                if getattr(run, "conclusion", "") == "failure" and not path.startswith(
                    "dynamic/"
                ):
                    failed.append(run)
                    if len(failed) >= max_runs:
                        break
        except GithubException as exc:
            logger.info("تعذّرت قراءة workflow runs لـ %s: %s", repo.full_name, exc)
        return failed

    @staticmethod
    def get_failed_jobs(run: Any) -> List[Any]:
        """إرجاع وظائف (jobs) التشغيل الفاشلة فقط."""
        jobs = []
        try:
            for job in run.jobs():
                if job.conclusion == "failure":
                    jobs.append(job)
        except GithubException as exc:
            logger.warning("تعذّرت قراءة وظائف التشغيل %s: %s", getattr(run, "id", "?"), exc)
        return jobs

    @staticmethod
    def download_job_log(job: Any, timeout: int = 90) -> str:
        """تنزيل السجل الكامل لوظيفة فاشلة وإرجاعه كنص.

        Raises:
            JobLogDownloadError: عند فشل التنزيل (شبكة/رابط منتهي/حظر نطاق).
        """
        import requests

        try:
            location = job.logs_url()
            resp = requests.get(location, timeout=timeout, stream=True)
            resp.raise_for_status()
            return resp.text
        except Exception as exc:  # noqa: BLE001 - فشل الشبكة بأنواعها كلها
            raise JobLogDownloadError(
                f"فشل تنزيل سجل الوظيفة {getattr(job, 'id', '?')}: {exc}"
            ) from exc

    @staticmethod
    def read_file_content(repo: Any, path: str) -> Optional[str]:
        """قراءة محتوى ملف نصي من الفرع الافتراضي (أو None إن غاب)."""
        try:
            obj = repo.get_contents(path)
            return obj.decoded_content.decode("utf-8", errors="replace")
        except GithubException:
            return None

    # ------------------------------------------------------------------ #
    # Fix application
    # ------------------------------------------------------------------ #
    def create_fix_branch_and_pr(
        self,
        repo: Any,
        branch_name: str,
        file_path: str,
        content: str,
        commit_msg: str,
        pr_title: str,
        pr_body: Optional[str] = None,
    ) -> str:
        """إنشاء فرع جديد، إضافة/تحديث ملف، ثم فتح Pull Request.

        Returns:
            URL of the created (or already existing) pull request.
        """
        default_branch = repo.get_branch(repo.default_branch)

        # إنشاء الفرع الجديد إذا لم يكن موجوداً
        try:
            repo.create_git_ref(
                ref=f"refs/heads/{branch_name}", sha=default_branch.commit.sha
            )
        except GithubException:
            logger.info("الفرع %s موجود مسبقاً في %s", branch_name, repo.full_name)

        # تحديث الملف إن كان موجوداً على الفرع، أو إنشاؤه
        try:
            file_obj = repo.get_contents(file_path, ref=branch_name)
            if isinstance(file_obj, list):  # مسار دليل - غير متوقع هنا
                raise GithubException(422, {"message": "Path is a directory"}, None)
            repo.update_file(
                path=file_path,
                message=commit_msg,
                content=content.encode("utf-8"),
                sha=file_obj.sha,
                branch=branch_name,
            )
        except GithubException as exc:
            if exc.status == 422 and "directory" in str(exc).lower():
                raise
            repo.create_file(
                path=file_path,
                message=commit_msg,
                content=content.encode("utf-8"),
                branch=branch_name,
            )

        # فتح Pull Request (مع تجنّب التكرار إذا كان هناك PR مفتوح لنفس الفرع)
        body = pr_body or f"{AGENT_BOT_SIGNATURE}\n\n"
        try:
            pr = repo.create_pull(
                title=pr_title,
                body=body,
                head=branch_name,
                base=repo.default_branch,
            )
            return pr.html_url
        except GithubException as exc:
            # GitHub returns 422 when a PR already exists for the head branch.
            existing = repo.get_pulls(
                state="open", head=f"{self.user.login}:{branch_name}"
            )
            if existing.totalCount > 0:
                url = existing[0].html_url
                logger.info("يوجد Pull Request مفتوح مسبقاً: %s", url)
                return url
            raise

    def post_issue_comment(self, repo: Any, issue_number: int, comment: str) -> str:
        """نشر تعليق على مشكلة مفتوحة (اقتراح الحل من الذكاء الاصطناعي).

        Returns:
            URL of the issue the comment was posted on.
        """
        issue = repo.get_issue(number=issue_number)
        issue.create_comment(comment)
        return issue.html_url
