"""طبقة التفاعل مع GitHub: فحص المستودعات واكتشاف النواقص وفتح Pull Requests.

GitHub API layer for Celia Repo Agent.

Responsibilities:
  * List the repositories owned by the authenticated user.
  * Audit each repository for common gaps (missing README / .gitignore /
    CI workflow, open issues).
  * Create fix branches, commit files and open pull requests.
  * Post AI-suggested solutions as comments on open issues.
"""

import logging
from typing import Any, Dict, List, Optional

from github import Auth, Github, GithubException

from config import Config

logger = logging.getLogger(__name__)

# Marker label used on PRs/comments created by the agent, so repeated runs
# can detect work that was already submitted instead of duplicating it.
AGENT_BOT_SIGNATURE = "🤖 **Auto-Fix generated by Celia Repo Agent**"


class GitHubService:
    """Thin wrapper around PyGithub with the audit/fix operations we need."""

    def __init__(self) -> None:
        auth = Auth.Token(Config.GITHUB_TOKEN)
        # `per_page=100` reduces the number of paginated requests.
        self.client = Github(auth=auth, per_page=100)
        self.user = self.client.get_user()
        logger.info("تم تسجيل الدخول إلى GitHub باسم: %s", self.user.login)

    # ------------------------------------------------------------------ #
    # Repository discovery
    # ------------------------------------------------------------------ #
    def get_all_repositories(self) -> List[Any]:
        """استرجاع جميع المستودعات التي يملكها المستخدم (بدون المستودعات المنسَّقة)."""
        owned: List[Any] = []
        for repo in self.user.get_repos(affiliation="owner"):
            try:
                if repo.owner.login == self.user.login and not repo.archived:
                    owned.append(repo)
            except GithubException as exc:  # pragma: no cover - defensive
                logger.warning("تعذّرت قراءة مستودع: %s", exc)
        return owned

    # ------------------------------------------------------------------ #
    # Auditing
    # ------------------------------------------------------------------ #
    def audit_repository(self, repo: Any) -> Dict[str, Any]:
        """فحص المستودع لاكتشاف النواقص والمشاكل.

        Returns:
            Dict containing repo metadata and a list of detected issues.
        """
        issues: List[Dict[str, Any]] = []

        # 1) README (any common variant counts as present)
        if not self._has_any_file(repo, ["README.md", "README.rst", "README.txt", "README"]):
            issues.append({"type": "missing_file", "target": "README.md"})

        # 2) .gitignore
        if not self._has_any_file(repo, [".gitignore"]):
            issues.append({"type": "missing_file", "target": ".gitignore"})

        # 3) CI/CD (GitHub Actions workflows)
        try:
            workflows = repo.get_workflows()
            if workflows.totalCount == 0:
                issues.append(
                    {"type": "missing_workflow", "target": ".github/workflows/ci.yml"}
                )
        except GithubException:
            # Repos without the Actions feature enabled, etc.
            pass

        # 4) Open issues (excluding pull requests)
        try:
            open_issues = repo.get_issues(state="open")
            for issue in open_issues:
                if not issue.pull_request:
                    issues.append(
                        {
                            "type": "open_issue",
                            "id": issue.number,
                            "title": issue.title,
                            "body": issue.body or "",
                        }
                    )
        except GithubException:
            pass

        return {
            "repo_name": repo.name,
            "full_name": repo.full_name,
            "default_branch": repo.default_branch,
            "issues": issues,
        }

    @staticmethod
    def _has_any_file(repo: Any, paths: List[str]) -> bool:
        """هل يوجد أي من المسارات المحددة في المستودع (على الفرع الافتراضي)؟"""
        for path in paths:
            try:
                repo.get_contents(path)
                return True
            except GithubException:
                continue
        return False

    # ------------------------------------------------------------------ #
    # Dependabot security alerts
    # ------------------------------------------------------------------ #
    def get_dependabot_alerts(self, repo: Any) -> List[Dict[str, Any]]:
        """جلب تنبيهات Dependabot المفتوحة الخاصة بحزم Python (pip).

        يتطلب ذلك صلاحية ``security_events`` على الـ Personal Access Token
        (أو ``security-events: read`` في GitHub Actions).

        Returns:
            قائمة بقواميس تصف الثغرات: رقم التنبيه، اسم الحزمة، الخطورة،
            النطاق المُصاب، النسخة المُصلِحة، ملخص الثغرة، معرّف GHSA،
            ومسار ملف الاعتماديات (manifest).
        """
        alerts: List[Dict[str, Any]] = []
        try:
            dependabot_alerts = repo.get_dependabot_alerts(state="open")
            for alert in dependabot_alerts:
                try:
                    vuln = alert.security_vulnerability
                    package = vuln.package
                    # تصفية ثغرات Python (pip) فقط
                    if (package.ecosystem or "").lower() != "pip":
                        continue

                    # ملاحظة: في PyGithub تكون first_patched_version قاموساً
                    # مثل {"identifier": "2.3.4"} وليست كائناً.
                    patched_info = vuln.first_patched_version or {}
                    patched_ver = (
                        patched_info.get("identifier")
                        if isinstance(patched_info, dict)
                        else getattr(patched_info, "identifier", None)
                    )

                    manifest = "requirements.txt"
                    try:
                        manifest = alert.dependency.manifest_path or manifest
                    except GithubException:
                        pass

                    alerts.append(
                        {
                            "number": alert.number,
                            "package_name": package.name,
                            "severity": vuln.severity,
                            "vulnerable_range": vuln.vulnerable_version_range,
                            "patched_version": patched_ver,
                            "summary": alert.security_advisory.summary,
                            "ghsa_id": alert.security_advisory.ghsa_id,
                            "manifest": manifest,
                        }
                    )
                except GithubException:
                    # تنبيه واحد غير قابل للقراءة يجب ألا يُسقط البقية.
                    continue
        except GithubException as exc:
            # 403/404: التوكن يفتقد صلاحية security_events أو Dependabot
            # غير مفعّل على المستودع — يتم التخطّي بهدوء.
            logger.info(
                "تعذّر جلب تنبيهات Dependabot لـ %s (قد يلزم تفعيل "
                "Dependabot أو منح صلاحية security_events): %s",
                repo.full_name,
                exc.status if hasattr(exc, "status") else exc,
            )
        return alerts

    # ------------------------------------------------------------------ #
    # Fix application
    # ------------------------------------------------------------------ #
    def create_fix_branch_and_pr(
        self,
        repo: Any,
        branch_name: str,
        file_path: str,
        content: str,
        commit_msg: str,
        pr_title: str,
        pr_body: Optional[str] = None,
    ) -> str:
        """إنشاء فرع جديد، إضافة/تحديث ملف، ثم فتح Pull Request.

        Returns:
            URL of the created (or already existing) pull request.
        """
        default_branch = repo.get_branch(repo.default_branch)

        # إنشاء الفرع الجديد إذا لم يكن موجوداً
        try:
            repo.create_git_ref(
                ref=f"refs/heads/{branch_name}", sha=default_branch.commit.sha
            )
        except GithubException:
            logger.info("الفرع %s موجود مسبقاً في %s", branch_name, repo.full_name)

        # تحديث الملف إن كان موجوداً على الفرع، أو إنشاؤه
        try:
            file_obj = repo.get_contents(file_path, ref=branch_name)
            if isinstance(file_obj, list):  # مسار دليل - غير متوقع هنا
                raise GithubException(422, {"message": "Path is a directory"}, None)
            repo.update_file(
                path=file_path,
                message=commit_msg,
                content=content.encode("utf-8"),
                sha=file_obj.sha,
                branch=branch_name,
            )
        except GithubException as exc:
            if exc.status == 422 and "directory" in str(exc).lower():
                raise
            repo.create_file(
                path=file_path,
                message=commit_msg,
                content=content.encode("utf-8"),
                branch=branch_name,
            )

        # فتح Pull Request (مع تجنّب التكرار إذا كان هناك PR مفتوح لنفس الفرع)
        body = pr_body or f"{AGENT_BOT_SIGNATURE}\n\n"
        try:
            pr = repo.create_pull(
                title=pr_title,
                body=body,
                head=branch_name,
                base=repo.default_branch,
            )
            return pr.html_url
        except GithubException as exc:
            # GitHub returns 422 when a PR already exists for the head branch.
            existing = repo.get_pulls(
                state="open", head=f"{self.user.login}:{branch_name}"
            )
            if existing.totalCount > 0:
                url = existing[0].html_url
                logger.info("يوجد Pull Request مفتوح مسبقاً: %s", url)
                return url
            raise

    def post_issue_comment(self, repo: Any, issue_number: int, comment: str) -> str:
        """نشر تعليق على مشكلة مفتوحة (اقتراح الحل من الذكاء الاصطناعي).

        Returns:
            URL of the issue the comment was posted on.
        """
        issue = repo.get_issue(number=issue_number)
        issue.create_comment(comment)
        return issue.html_url
